### ISSUE TITLE
Making JavaScript Functioning

### ISSUE THREAD

**Issue by Stach13** [newtfire/Lord-of-the-Rings#1]
- Include CSS inside SVG document, so that you can create selectors in JS. 
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style 
- Take a look at the Hamilton Project website for an example on how to use this() with event listeners.

**Comment by ebeshero** [comment]
A useful resource on the `@style` attribute on SVG elements:
https://www.geeksforgeeks.org/svg-style-attribute/

https://stackoverflow.com/questions/24578837/remove-or-hide-svg-element
